spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_application_system_db
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
api:
  security:
    token:
      secret: ${JWT_SECRET:super-secret_key}