CREATE TABLE employee
(
    employee_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_name VARCHAR(255)                            NOT NULL,
    occupancy     SMALLINT                                NOT NULL,
    hiring_date   date                                    NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    city          VARCHAR(255)                            NOT NULL,
    street        VARCHAR(255)                            NOT NULL,
    zip_code      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (employee_id)
);