CREATE TABLE item
(
    item_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name  VARCHAR(255)                            NOT NULL,
    item_price DECIMAL                                 NOT NULL,
    item_desc  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (item_id)
);

ALTER TABLE item
    ADD CONSTRAINT uc_item_item_name UNIQUE (item_name);