CREATE TABLE ingredient
(
    ingredient_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ingredient_name   VARCHAR(255)                            NOT NULL,
    quantity_in_stock INTEGER                                 NOT NULL,
    item_item_id      BIGINT,
    CONSTRAINT pk_ingredient PRIMARY KEY (ingredient_id)
);

ALTER TABLE ingredient
    ADD CONSTRAINT uc_ingredient_ingredient_name UNIQUE (ingredient_name);

ALTER TABLE ingredient
    ADD CONSTRAINT FK_INGREDIENT_ON_ITEM_ITEM FOREIGN KEY (item_item_id) REFERENCES item (item_id);