CREATE TABLE eating_table
(
    table_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_capacity INTEGER                                 NOT NULL,
    available      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_eating_table PRIMARY KEY (table_id)
);