CREATE TABLE ingredient_usages
(
    usage_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ingredient_id BIGINT                                  NOT NULL,
    item_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_ingredient_usages PRIMARY KEY (usage_id)
);

ALTER TABLE ingredient_usages
    ADD CONSTRAINT FK_INGREDIENT_USAGES_ON_INGREDIENT FOREIGN KEY (ingredient_id) REFERENCES ingredient (ingredient_id);

ALTER TABLE ingredient_usages
    ADD CONSTRAINT FK_INGREDIENT_USAGES_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (item_id);